### ISSUE TITLE
Consistently crashes when charger connected

### ISSUE THREAD

**Issue by Grail01** [albertakhmetov/flowOSD#8]
Love FlowOSD! Unistalled ASUS Crate and only use FlowOSD. However, noticing that I have to re-open flowOSD about once a day. Running on a Windows 11 GV301RC with standard Asus 100W charger. It appears to fail when I plug the charger in.

In event viewer I can see the following events occurring each time:
- Information - ERCService -  PowerEvent handled successfully by the service.
- Error - .NET Runtime - Application: flowOSD.exe
CoreCLR Version: 7.0.523.17405
.NET Version: 7.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ApplicationException: Can't change display refresh rate. Error code: -1.
   at flowOSD.Hardware.Display.SetRefreshRate(Nullable`1 value)
   at flowOSD.Services.RefreshRateService.Update(PowerSource powerSource, DeviceState displayState)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
- Error - Application Error - Faulting application name: flowOSD.exe, version: 2.1.2.0, time stamp: 0x641de100
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1680, time stamp: 0x0a48b2f9
Exception code: 0xe0434352
Fault offset: 0x000000000006536c
Faulting process id: 0x0x9FA0
Faulting application start time: 0x0x1D98BB202C2B6E6
Faulting application path: C:\Program Files\flowOSD\flowOSD.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: e2be6dd7-089f-4483-b48e-c9eafe7937dc
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Grail01** [comment]
I get a message quite often when this happens that says something about it failing to change the Screen Refresh rate.

**Comment by albertakhmetov** [comment]
Hi,  this issue is fixed in flowOSD 3. Sorry for delay
